@extends('layouts.app')
@section('title', 'Grupe pristupa')
@section('content')
<div class="page-heading"><div><span class="eyebrow">Korisnici</span><h1>Grupe pristupa</h1><p>Podesi dozvole i kategorijski pristup za standardne korisnike.</p></div></div>
<section class="panel form-section"><h2>Dodaj grupu</h2><form method="post" action="{{ route('admin.user-groups.store') }}" class="stack-form">@csrf
<div class="field-grid"><label><span>Naziv</span><input name="name" required></label><label><span>Slug</span><input name="slug" placeholder="Automatski ako ostane prazno"></label><label class="field-span-2"><span>Opis</span><textarea name="description"></textarea></label><label><span>Status</span><select name="status"><option value="active">Aktivna</option><option value="inactive">Neaktivna</option></select></label><label><span>Pristup kategorijama</span><select name="category_access_mode"><option value="all">Sve kategorije</option><option value="selected">Samo izabrane</option><option value="none">Bez kategorija</option></select></label><label><span>Redosled</span><input type="number" name="sort_order" min="0" value="0"></label><label class="check-card"><input type="checkbox" name="include_uncategorized" value="1" checked><span>Uključi artikle bez kategorije</span></label></div>
<div class="permission-grid"><div><strong>Dozvole</strong>@foreach($permissions as $permission)<label class="check-card"><input type="checkbox" name="permissions[]" value="{{ $permission->id }}"><span>{{ $permission->name }}<small>{{ $permission->description }}</small></span></label>@endforeach</div><div><strong>Kategorije</strong>@foreach($categories as $category)<label class="check-card"><input type="checkbox" name="categories[]" value="{{ $category->id }}"><span>{{ $category->name }}</span></label>@endforeach</div></div>
<button class="button button-primary" type="submit">Dodaj grupu</button></form></section>
<div class="dictionary-grid group-grid">@foreach($groups as $group)<article class="panel dictionary-card"><form method="post" action="{{ route('admin.user-groups.update', $group) }}">@csrf @method('put')
<div class="card-header-row"><div><strong>{{ $group->name }}</strong><small>{{ $group->users_count }} korisnika</small></div><span class="status-badge status-{{ $group->status === 'active' ? 'active' : 'archived' }}">{{ $group->status }}</span></div>
<div class="field-grid"><label><span>Naziv</span><input name="name" value="{{ $group->name }}" required></label><label><span>Slug</span><input name="slug" value="{{ $group->slug }}"></label><label class="field-span-2"><span>Opis</span><textarea name="description">{{ $group->description }}</textarea></label><label><span>Status</span><select name="status"><option value="active" @selected($group->status==='active')>Aktivna</option><option value="inactive" @selected($group->status==='inactive')>Neaktivna</option></select></label><label><span>Pristup kategorijama</span><select name="category_access_mode"><option value="all" @selected($group->category_access_mode==='all')>Sve</option><option value="selected" @selected($group->category_access_mode==='selected')>Izabrane</option><option value="none" @selected($group->category_access_mode==='none')>Bez pristupa</option></select></label><label><span>Redosled</span><input type="number" name="sort_order" min="0" value="{{ $group->sort_order }}"></label><label class="check-card"><input type="checkbox" name="include_uncategorized" value="1" @checked($group->include_uncategorized)><span>Uključi artikle bez kategorije</span></label></div>
<div class="permission-grid"><div><strong>Dozvole</strong>@foreach($permissions as $permission)<label class="check-card"><input type="checkbox" name="permissions[]" value="{{ $permission->id }}" @checked($group->permissions->contains($permission->id))><span>{{ $permission->name }}</span></label>@endforeach</div><div><strong>Kategorije</strong>@foreach($categories as $category)<label class="check-card"><input type="checkbox" name="categories[]" value="{{ $category->id }}" @checked($group->categories->contains($category->id))><span>{{ $category->name }}</span></label>@endforeach</div></div>
<div class="card-actions"><button class="button button-primary button-small" type="submit">Sačuvaj</button><button class="button button-danger button-small" type="submit" form="delete-group-{{ $group->id }}">Obriši</button></div></form><form id="delete-group-{{ $group->id }}" method="post" action="{{ route('admin.user-groups.destroy', $group) }}">@csrf @method('delete')</form></article>@endforeach</div>
@endsection
