@extends('layouts.app')
@section('title','Bulk izmena artikala')
@section('content')
<a class="back-link" href="{{ route('catalog.index') }}">← Nazad na artikle</a>
<div class="page-heading"><div><span class="eyebrow">Pametno upravljanje katalogom</span><h1>Bulk izmena artikala</h1><p>Promene se prvo pregledaju, a zatim posebno potvrđuju.</p></div></div>
@if($selectedProducts->isEmpty())
<section class="panel empty-state"><h2>Nema izabranih artikala</h2><p>Vrati se na listu artikala, označi željene redove i klikni „Bulk izmena”.</p><a class="button button-primary" href="{{ route('catalog.index') }}">Otvori listu artikala</a></section>
@else
<form method="post" action="{{ route('admin.products.bulk.process') }}">@csrf
@foreach($selectedProducts as $selected)<input type="hidden" name="product_ids[]" value="{{ $selected->id }}">@endforeach
<div class="admin-form-grid"><div class="form-main">
<section class="panel form-section"><div class="section-heading-row"><div><h2>Izabrani artikli</h2><p class="muted">{{ $selectedProducts->count() }} artikala</p></div></div><div class="bulk-selected-list">@foreach($selectedProducts as $selected)<span><strong>{{ $selected->sku }}</strong> {{ $selected->name }} <small>{{ $selected->completeness_percent }}%</small></span>@endforeach</div></section>
<section class="panel form-section"><h2>Osnovni podaci</h2><div class="field-grid">
<label class="check-card"><input type="checkbox" name="apply_status" value="1" @checked(old('apply_status',$apply_status??false))><span>Promeni status</span></label><label><span>Novi status</span><select name="status">@foreach(['draft'=>'Nacrt','active'=>'Aktivan','inactive'=>'Neaktivan'] as $v=>$l)<option value="{{ $v }}" @selected(old('status',$status??'draft')===$v)>{{ $l }}</option>@endforeach</select></label>
<label class="check-card"><input type="checkbox" name="apply_brand" value="1" @checked(old('apply_brand',$apply_brand??false))><span>Promeni brend</span></label><label><span>Brend</span><select name="brand_id"><option value="">Bez brenda</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected((int)old('brand_id',$brand_id??0)===$brand->id)>{{ $brand->name }}</option>@endforeach</select></label>
<label class="check-card"><input type="checkbox" name="apply_line" value="1" @checked(old('apply_line',$apply_line??false))><span>Promeni liniju</span></label><label><span>Linija</span><select name="product_line_id"><option value="">Bez linije</option>@foreach($lines as $line)<option value="{{ $line->id }}" @selected((int)old('product_line_id',$product_line_id??0)===$line->id)>{{ $line->brand?->name }} · {{ $line->name }}</option>@endforeach</select></label>
<label class="check-card"><input type="checkbox" name="apply_type" value="1" @checked(old('apply_type',$apply_type??false))><span>Promeni tip / šablon</span></label><label><span>Tip artikla</span><select name="product_type_id"><option value="">Bez tipa</option>@foreach($types as $type)<option value="{{ $type->id }}" @selected((int)old('product_type_id',$product_type_id??0)===$type->id)>{{ $type->name }}@if($type->category) · {{ $type->category->name }}@endif</option>@endforeach</select><small class="muted">Kategorija se automatski dodeljuje prema tipu, a nepovezane specifikacije se uklanjaju.</small></label>
</div></section>
<section class="panel form-section"><h2>Cena</h2><div class="field-grid"><label><span>Operacija nad cenom</span><select name="price_action"><option value="">Bez promene</option>@foreach(['set'=>'Postavi cenu','increase_percent'=>'Povećaj za %','decrease_percent'=>'Smanji za %','increase_fixed'=>'Povećaj za iznos','decrease_fixed'=>'Smanji za iznos'] as $v=>$l)<option value="{{ $v }}" @selected(old('price_action',$price_action??'')===$v)>{{ $l }}</option>@endforeach</select></label><label><span>Vrednost</span><input type="number" step="0.01" min="0" name="price_value" value="{{ old('price_value',$price_value??'') }}"></label></div></section>
<section class="panel form-section"><h2>Specifikacije i nazivi</h2><div class="field-grid"><label><span>Operacija nad specifikacijom</span><select name="specification_action"><option value="">Bez promene</option><option value="set" @selected(old('specification_action',$specification_action??'')==='set')>Postavi vrednost</option><option value="clear" @selected(old('specification_action',$specification_action??'')==='clear')>Ukloni vrednost</option></select></label><label><span>Polje</span><select name="specification_field_id"><option value="">Izaberi</option>@foreach($fields as $field)<option value="{{ $field->id }}" @selected((int)old('specification_field_id',$specification_field_id??0)===$field->id)>{{ $field->name }} · {{ $field->data_type }}</option>@endforeach</select></label><label><span>Vrednost</span><input name="specification_value" maxlength="1000" value="{{ old('specification_value',$specification_value??'') }}"></label><label><span>Dodatni detalj</span><input name="specification_detail" maxlength="500" value="{{ old('specification_detail',$specification_detail??'') }}"></label><label class="check-card field-span-2"><input type="checkbox" name="regenerate_names" value="1" @checked(old('regenerate_names',$regenerate_names??false))><span>Regeneriši nazive prema šablonu nakon svih promena</span></label></div></section>
@if(isset($preview))<section class="panel form-section preview-panel"><h2>Pregled promena</h2><p><strong>{{ $preview['count'] }}</strong> artikala biće izmenjeno.</p><ul>@foreach($preview['summary'] as $line)<li>{{ $line }}</li>@endforeach</ul><div class="bulk-preview-products">@foreach($preview['products'] as $row)<span>{{ $row['sku'] }} · {{ $row['name'] }}</span>@endforeach</div></section>@endif
</div><aside class="form-side"><section class="panel form-section sticky-card"><h2>Izvršenje</h2><p class="muted">Prvo pregledaj tačan obim promena. Izvršenje se evidentira u audit logu za svaki artikal.</p>@if(isset($preview))<button class="button button-primary button-large" name="mode" value="execute" onclick="return confirm('Potvrđuješ bulk izmenu {{ $preview['count'] }} artikala?')">Izvrši potvrđene promene</button><button class="button button-ghost" name="mode" value="preview">Osveži pregled</button>@else<button class="button button-primary button-large" name="mode" value="preview">Pregledaj promene</button>@endif</section></aside></div>
</form>
@endif
@endsection
