@extends('layouts.app')
@section('title', 'Administracija artikala')
@section('content')
<div class="page-heading"><div><span class="eyebrow">Administracija kataloga</span><h1>Artikli</h1><p>Dodavanje, izmena, kloniranje, bulk operacije i upravljanje šablonima artikala.</p></div><div class="page-heading-actions"><a class="button button-ghost" href="{{ route('admin.products.bulk') }}">Bulk centar</a><a class="button button-primary" href="{{ route('admin.products.create') }}">+ Dodaj artikal</a></div></div>
<form class="filter-panel admin-filter" method="get" data-correlated-spec-filter-form>
<label class="search-field"><span>Pretraga</span><input name="q" value="{{ request('q') }}" placeholder="Naziv ili SKU"></label>
<label><span>Status</span><select name="status"><option value="">Svi</option>@foreach(['draft'=>'Nacrt','active'=>'Aktivan','inactive'=>'Neaktivan','archived'=>'Arhiviran'] as $v=>$l)<option value="{{ $v }}" @selected(request('status')===$v)>{{ $l }}</option>@endforeach</select></label>
<label><span>Tip</span><select name="product_type_id" data-filter-product-type><option value="">Svi tipovi</option>@foreach($types as $type)<option value="{{ $type->id }}" @selected((int)request('product_type_id')===$type->id)>{{ $type->name }}</option>@endforeach</select></label>
<label><span>Brend</span><select name="brand_id" data-filter-brand><option value="">Svi</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected((int)request('brand_id')===$brand->id)>{{ $brand->name }}</option>@endforeach</select></label>
<label><span>Linija</span><select name="product_line_id" data-filter-line><option value="">Sve linije</option>@foreach($lines as $line)<option value="{{ $line->id }}" data-brand-id="{{ $line->brand_id }}" @selected((int)request('product_line_id')===$line->id)>{{ $line->name }}</option>@endforeach</select></label>
@include('partials.correlated-specification-filters', ['filterFields' => $filterFields])
<div class="filter-actions"><button class="button button-primary">Primeni</button><a class="button button-ghost" href="{{ route('admin.products.index') }}">Reset</a></div>
</form>
<form method="get" action="{{ route('admin.products.bulk') }}" data-bulk-selection-form>
<div class="bulk-selection-bar"><button class="button button-primary button-small" type="submit">Bulk izmena izabranih</button><span data-bulk-count>0 izabrano</span></div>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th><input type="checkbox" data-select-all aria-label="Izaberi sve artikle na stranici"></th><th>Artikal</th><th>Brend / linija</th><th>Status</th><th>Kompletnost</th><th>Cena</th><th>Lager</th><th>Izmena</th><th></th></tr></thead><tbody>
@forelse($products as $product)<tr><td data-label="Izbor"><input type="checkbox" name="product_ids[]" value="{{ $product->id }}" data-product-select></td><td data-label="Artikal"><div class="table-product"><div class="table-thumb">@if($product->primaryImage)<img src="{{ $product->primaryImage->url }}" alt="">@else ◫ @endif</div><div><strong>{{ $product->name }}</strong><small>SKU {{ $product->sku }} · {{ $product->images_count }} slika @if($product->variants_count)· {{ $product->active_variants_count }}/{{ $product->variants_count }} aktivnih varijanti @endif</small></div></div></td><td data-label="Brend / linija">{{ $product->brand?->name ?? '—' }}@if($product->line)<small class="muted"> · {{ $product->line->name }}</small>@endif</td><td data-label="Status"><span class="status-badge status-{{ $product->deleted_at ? 'archived' : $product->status }}">{{ $product->deleted_at ? 'Arhiviran' : $product->status }}</span></td><td data-label="Kompletnost"><div class="mini-completeness"><span><i style="width:{{ (int)$product->completeness_percent }}%"></i></span><b>{{ (int)$product->completeness_percent }}%</b></div></td><td data-label="Cena">{{ number_format((float)$product->price_amount,2,',','.') }} {{ $product->price_currency }}</td><td data-label="Lager">{{ $product->stock_quantity }}</td><td data-label="Izmena">{{ optional($product->updated_at)->format('d.m.Y. H:i') }}</td><td class="row-actions"><a class="button button-small button-ghost" href="{{ route('admin.products.edit',$product) }}">Izmeni</a><a class="button button-small button-ghost" href="{{ route('admin.products.clone',$product) }}">Kloniraj</a><a class="button button-small button-ghost" href="{{ route('admin.products.variants.index',$product) }}">Varijante</a>@can('catalog.manage_images')<a class="button button-small button-ghost" href="{{ route('admin.products.images.index',$product) }}">Slike</a>@endcan</td></tr>@empty<tr><td colspan="9"><div class="empty-state">Nema artikala za izabrane filtere.</div></td></tr>@endforelse
</tbody></table></div></form><div class="pagination-wrap">{{ $products->links() }}</div>
@endsection
@push('scripts')
@include('partials.correlated-specification-filter-script')
<script>
(() => { const all=document.querySelector('[data-select-all]'); const boxes=Array.from(document.querySelectorAll('[data-product-select]')); const count=document.querySelector('[data-bulk-count]'); const refresh=()=>{const n=boxes.filter(b=>b.checked).length;if(count)count.textContent=`${n} izabrano`;if(all){all.checked=n>0&&n===boxes.length;all.indeterminate=n>0&&n<boxes.length;}}; all?.addEventListener('change',()=>{boxes.forEach(b=>b.checked=all.checked);refresh();}); boxes.forEach(b=>b.addEventListener('change',refresh)); refresh(); })();
</script>
@endpush
