import { StyleSheet, Text, View } from 'react-native';
import { spacing, typography, type AppColors } from '@/constants/theme';
import { useAppTheme } from '@/theme/app-theme';
export type StatusTimelineTone='neutral'|'primary'|'success'|'warning'|'danger';
export type StatusTimelineItem={key:string;title:string;description?:string|null;meta?:string|null;tone?:StatusTimelineTone;current?:boolean};
type Props={items:readonly StatusTimelineItem[];emptyLabel?:string};
export function StatusTimeline({items,emptyLabel='Nema istorije statusa.'}:Props){const { colors: theme } = useAppTheme();const styles=createStyles(theme);if(items.length===0)return <Text style={styles.empty}>{emptyLabel}</Text>;return <View>{items.map((item,index)=>{const tone=item.tone??(item.current?'primary':'neutral');const dotColor=resolveToneColor(theme,tone);const last=index===items.length-1;return <View key={item.key} style={styles.row}><View style={styles.rail}><View style={[styles.dot,{backgroundColor:dotColor}]}/>{!last?<View style={styles.line}/>:null}</View><View style={[styles.content,last?styles.last:null]}><View style={styles.heading}><Text style={styles.title}>{item.title}</Text>{item.current?<Text style={styles.current}>TRENUTNO</Text>:null}</View>{item.description?<Text style={styles.description}>{item.description}</Text>:null}{item.meta?<Text style={styles.meta}>{item.meta}</Text>:null}</View></View>;})}</View>;}
function resolveToneColor(theme:AppColors,tone:StatusTimelineTone):string{if(tone==='primary')return theme.primary;if(tone==='success')return theme.success;if(tone==='warning')return theme.warning;if(tone==='danger')return theme.danger;return theme.muted;}
function createStyles(theme:AppColors){return StyleSheet.create({row:{flexDirection:'row',gap:spacing.md},rail:{width:18,alignItems:'center'},dot:{width:12,height:12,borderRadius:999,marginTop:4},line:{width:2,flex:1,minHeight:36,backgroundColor:theme.line,marginVertical:4},content:{flex:1,gap:spacing.xs,paddingBottom:spacing.lg},last:{paddingBottom:0},heading:{flexDirection:'row',alignItems:'center',gap:spacing.sm},title:{...typography.body,color:theme.ink,fontWeight:'800',flex:1},current:{...typography.small,color:theme.primary,fontWeight:'800'},description:{...typography.body,color:theme.muted},meta:{...typography.small,color:theme.muted},empty:{...typography.body,color:theme.muted}});}
