@extends('layouts.app')
@section('title','Izveštaji i profitabilnost')
@section('content')

<div class="page-heading"><div><span class="eyebrow">Management Analytics</span><h1>Izveštaji i profitabilnost</h1><p>Promet, bruto marža, provizije, refundacije, servisni troškovi, lager i potraživanja na jednom mestu.</p></div>@can('reports.export')<div class="report-export-actions"><a class="button button-ghost" href="{{ route('admin.reports.management.csv',request()->query()) }}"><x-icon name="download" /> CSV</a><a class="button button-primary" target="_blank" rel="noopener" href="{{ route('admin.reports.management.pdf',request()->query()) }}"><x-icon name="file-text" /> PDF</a></div>@endcan</div>

@if($issues!==[])<div class="alert alert-warning"><strong>Upravljački izveštaji nisu spremni.</strong><span>{{ implode(' ',$issues) }}</span><code>php artisan app:management-reports-doctor --repair</code></div>@endif

<form class="filter-panel" method="get" action="{{ route('admin.reports.index') }}">
<label><span>Od</span><input type="date" name="date_from" value="{{ $filters['date_from'] }}"></label><label><span>Do</span><input type="date" name="date_to" value="{{ $filters['date_to'] }}"></label>
<label><span>Obuhvat</span><select name="scope"><option value="completed" @selected($filters['scope']==='completed')>Kompletirane porudžbine</option><option value="active" @selected($filters['scope']==='active')>Sve osim otkazanih</option><option value="all" @selected($filters['scope']==='all')>Sve porudžbine</option></select></label>
<label><span>Grupisanje</span><select name="group_by"><option value="brand" @selected($filters['group_by']==='brand')>Brend</option><option value="line" @selected($filters['group_by']==='line')>Linija</option><option value="type" @selected($filters['group_by']==='type')>Tip artikla</option><option value="product" @selected($filters['group_by']==='product')>Proizvod</option><option value="admin" @selected($filters['group_by']==='admin')>Odgovorno lice</option></select></label>
@if($suppliers->isNotEmpty())<label><span>Odgovorno lice</span><select name="supplier_user_id"><option value="0">Svi</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected((int)$filters['supplier_user_id']===(int)$supplier->id)>{{ $supplier->displayName() }}</option>@endforeach</select></label>@endif
<label><span>Brend</span><select name="brand"><option value="">Svi</option>@foreach($dimensions['brands'] as $value)<option @selected($filters['brand']===$value)>{{ $value }}</option>@endforeach</select></label>
<label><span>Linija</span><select name="line"><option value="">Sve</option>@foreach($dimensions['lines'] as $value)<option @selected($filters['line']===$value)>{{ $value }}</option>@endforeach</select></label>
<label><span>Tip</span><select name="type"><option value="">Svi</option>@foreach($dimensions['types'] as $value)<option @selected($filters['type']===$value)>{{ $value }}</option>@endforeach</select></label>
<label><span>Proizvod / SKU</span><input name="q" value="{{ $filters['q'] }}" placeholder="Naziv ili SKU"></label><div class="filter-actions"><button class="button button-primary">Primeni</button><a class="button button-ghost" href="{{ route('admin.reports.index') }}">Reset</a></div>
</form>

@if($report)
@php($s=$report['summary'])
<div class="analytics-grid">
<div class="analytics-card"><small>Prihod</small><strong>{{ number_format($s['revenue_rsd'],2,',','.') }} RSD</strong><em>{{ number_format($s['orders_count'],0,',','.') }} porudžbina · prosek {{ number_format($s['average_order_rsd'],2,',','.') }}</em></div>
<div class="analytics-card"><small>Bruto dobit</small><strong class="{{ $s['gross_profit_rsd']>=0?'analytics-good':'analytics-bad' }}">{{ number_format($s['gross_profit_rsd'],2,',','.') }} RSD</strong><em>Bruto marža {{ number_format($s['gross_margin_percent'],2,',','.') }}%</em></div>
<div class="analytics-card"><small>Neto doprinos</small><strong class="{{ $s['net_contribution_rsd']>=0?'analytics-good':'analytics-bad' }}">{{ number_format($s['net_contribution_rsd'],2,',','.') }} RSD</strong><em>Neto marža {{ number_format($s['net_margin_percent'],2,',','.') }}%</em></div>
<div class="analytics-card"><small>Pokrivenost nabavne cene</small><strong class="{{ $s['cost_coverage_percent']>=95?'analytics-good':'analytics-warning' }}">{{ number_format($s['cost_coverage_percent'],1,',','.') }}%</strong><em>{{ $s['missing_cost_lines'] }} stavki bez troška · {{ number_format($s['revenue_missing_cost_rsd'],2,',','.') }} RSD prometa</em></div>
<div class="analytics-card"><small>Nabavna vrednost</small><strong>{{ number_format($s['cogs_rsd'],2,',','.') }} RSD</strong><em>Snapshot trošak prodatih artikala</em></div>
<div class="analytics-card"><small>Provizije</small><strong>{{ number_format($s['commissions_rsd'],2,',','.') }} RSD</strong><em>EUR provizije preračunate istorijskim kursom</em></div>
<div class="analytics-card"><small>Refundacije + servis</small><strong>{{ number_format($s['refunds_rsd']+$s['service_cost_rsd'],2,',','.') }} RSD</strong><em>Refundacije {{ number_format($s['refunds_rsd'],2,',','.') }} · servis {{ number_format($s['service_cost_rsd'],2,',','.') }}</em></div>
<div class="analytics-card"><small>Otvorena potraživanja</small><strong class="analytics-warning">{{ number_format($s['outstanding_rsd'],2,',','.') }} RSD</strong><em>Preostali saldo izabranih porudžbina</em></div>
</div>

<div class="analytics-two"><section class="panel form-section"><div class="section-heading-row"><div><h2>Trend prometa i bruto dobiti</h2><p class="muted">{{ $report['period_label'] }}</p></div></div>@php($maxTrend=max(1,(float)collect($report['trend'])->max('revenue_rsd')))@forelse($report['trend'] as $row)<div class="analytics-bar-row"><small>{{ $row['period'] }}</small><div class="analytics-bar"><i style="width:{{ min(100,($row['revenue_rsd']/$maxTrend)*100) }}%"></i></div><strong>{{ number_format($row['revenue_rsd'],0,',','.') }} RSD</strong></div>@empty<p class="muted">Nema podataka za trend.</p>@endforelse</section>
<section class="panel form-section"><h2>Kvalitet finansijskih podataka</h2><dl class="detail-list"><dt>Pokriven promet</dt><dd>{{ number_format($s['known_revenue_rsd'],2,',','.') }} RSD</dd><dt>Promet bez nabavne cene</dt><dd>{{ number_format($s['revenue_missing_cost_rsd'],2,',','.') }} RSD</dd><dt>Stavke bez troška</dt><dd>{{ $s['missing_cost_lines'] }}</dd><dt>Preporuka</dt><dd>@if($s['cost_coverage_percent']<95)<span class="analytics-warning">Dopuniti nabavne cene proizvoda.</span>@else<span class="analytics-good">Podaci su dovoljno pokriveni.</span>@endif</dd></dl></section></div>

<section class="panel form-section"><div class="section-heading-row"><div><h2>Profitabilnost po segmentu</h2><p class="muted">Grupisano: {{ ['brand'=>'brend','line'=>'linija','type'=>'tip artikla','product'=>'proizvod','admin'=>'odgovorno lice'][$filters['group_by']] }}</p></div></div><div class="admin-table-wrap"><table class="admin-table analytics-table"><thead><tr><th>Segment</th><th>Porudžbine</th><th>Komada</th><th>Prihod</th><th>Nabavna vrednost</th><th>Bruto dobit</th><th>Marža</th><th>Pokrivenost</th></tr></thead><tbody>@forelse($report['segments'] as $row)<tr><td><strong>{{ $row['label'] }}</strong></td><td>{{ $row['orders_count'] }}</td><td>{{ $row['units_count'] }}</td><td>{{ number_format($row['revenue_rsd'],2,',','.') }} RSD</td><td>{{ number_format($row['cogs_rsd'],2,',','.') }} RSD</td><td class="{{ $row['gross_profit_rsd']>=0?'analytics-good':'analytics-bad' }}">{{ number_format($row['gross_profit_rsd'],2,',','.') }} RSD</td><td>{{ number_format($row['gross_margin_percent'],1,',','.') }}%</td><td>{{ number_format($row['cost_coverage_percent'],1,',','.') }}%</td></tr>@empty<tr><td colspan="8">Nema podataka.</td></tr>@endforelse</tbody></table></div></section>

<div class="analytics-three"><section class="panel form-section"><h2>Lager i kapital</h2><dl class="detail-list"><dt>Vrednost lagera</dt><dd><strong>{{ number_format($report['inventory']['value_rsd'],2,',','.') }} RSD</strong></dd><dt>Komada</dt><dd>{{ $report['inventory']['units_count'] }}</dd><dt>Bez nabavne cene</dt><dd>{{ $report['inventory']['missing_cost_items'] }}</dd><dt>Spori lager 90+ dana</dt><dd>{{ $report['inventory']['slow_items'] }}</dd></dl><h3>Starost vrednosti lagera</h3><div class="analytics-aging">@foreach(['0_30'=>'0–30','31_60'=>'31–60','61_90'=>'61–90','91_180'=>'91–180','over_180'=>'180+'] as $key=>$label)<div><small>{{ $label }} dana</small><strong>{{ number_format($report['inventory']['aging'][$key]??0,0,',','.') }}</strong></div>@endforeach</div></section>
<section class="panel form-section"><h2>Potraživanja</h2><dl class="detail-list"><dt>Otvorene porudžbine</dt><dd>{{ $report['receivables']['open_orders'] }}</dd><dt>Ukupan saldo</dt><dd><strong>{{ number_format($report['receivables']['outstanding_rsd'],2,',','.') }} RSD</strong></dd></dl><h3>Aging duga</h3>@foreach(['not_due'=>'Nije dospelo','1_7'=>'1–7','8_15'=>'8–15','16_30'=>'16–30','31_60'=>'31–60','61_90'=>'61–90','over_90'=>'90+'] as $key=>$label)<div class="analytics-bar-row"><small>{{ $label }}</small><div class="analytics-bar"><i style="width:{{ $report['receivables']['outstanding_rsd']>0?min(100,($report['receivables']['aging'][$key]/$report['receivables']['outstanding_rsd'])*100):0 }}%"></i></div><strong>{{ number_format($report['receivables']['aging'][$key],0,',','.') }}</strong></div>@endforeach</section>
<section class="panel form-section"><h2>Postprodaja</h2><dl class="detail-list"><dt>Ukupno slučajeva</dt><dd>{{ $report['after_sales']['cases'] }}</dd><dt>Otvoreno</dt><dd>{{ $report['after_sales']['open'] }}</dd><dt>Prekoračen SLA</dt><dd>{{ $report['after_sales']['overdue'] }}</dd><dt>Stopa reklamacija</dt><dd>{{ number_format($report['after_sales']['complaint_rate_percent'],2,',','.') }}%</dd><dt>Servisni trošak</dt><dd>{{ number_format($report['after_sales']['service_cost_rsd'],2,',','.') }} RSD</dd></dl></section></div>

<section class="panel form-section"><div class="section-heading-row"><div><h2>Najveća vrednost lagera</h2><p class="muted">Artikli koji vezuju najviše kapitala.</p></div><a class="button button-ghost button-small" href="{{ route('admin.reports.inventory.csv') }}">Postojeći lager CSV</a></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>SKU</th><th>Artikal</th><th>Količina</th><th>Jedinični trošak</th><th>Vrednost</th><th>Starost</th></tr></thead><tbody>@forelse(array_slice($report['inventory']['top_value'],0,15) as $row)<tr><td>{{ $row['sku'] }}</td><td>{{ $row['name'] }}</td><td>{{ $row['quantity'] }}</td><td>{{ $row['has_cost']?number_format($row['unit_cost_rsd'],2,',','.').' RSD':'Nedostaje' }}</td><td>{{ number_format($row['value_rsd'],2,',','.') }} RSD</td><td>{{ $row['age_days'] }} dana</td></tr>@empty<tr><td colspan="6">Nema lagera.</td></tr>@endforelse</tbody></table></div></section>
@endif

@can('reports.manage')
<div class="analytics-two"><section class="panel form-section"><h2>Zakazano slanje izveštaja</h2><p class="muted">Svaki primalac dobija zaseban e-mail sa PDF/CSV prilogom.</p><form method="post" action="{{ route('admin.report-schedules.store') }}" class="analytics-form-grid">@csrf
<label class="span-2"><span>Naziv rasporeda</span><input name="name" required placeholder="Nedeljni upravljački izveštaj"></label><label><span>Tip</span><select name="report_type"><option value="management_summary">Kompletan upravljački</option><option value="profitability">Profitabilnost</option><option value="inventory">Lager</option><option value="receivables">Potraživanja</option><option value="after_sales">Postprodaja</option></select></label><label><span>Učestalost</span><select name="frequency"><option value="daily">Dnevno</option><option value="weekly" selected>Nedeljno</option><option value="monthly">Mesečno</option></select></label>
<label><span>Vreme</span><input type="time" name="send_time" value="08:00" required></label><label><span>Dan nedelje</span><select name="weekday">@foreach([1=>'Ponedeljak',2=>'Utorak',3=>'Sreda',4=>'Četvrtak',5=>'Petak',6=>'Subota',7=>'Nedelja'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label><span>Dan u mesecu</span><input type="number" name="month_day" min="1" max="28" value="1"></label><label><span>Vremenska zona</span><input name="timezone" value="Europe/Belgrade" required></label>
<label class="span-4"><span>Primaoci — jedan po redu</span><textarea name="recipients" rows="3" required placeholder="direktor@example.com&#10;finansije@example.com"></textarea></label><div class="span-2"><span>Prilozi</span><label class="checkbox-row"><input type="checkbox" name="formats[]" value="pdf" checked> PDF</label><label class="checkbox-row"><input type="checkbox" name="formats[]" value="csv"> CSV</label></div><div class="span-2"><span>Obuhvat rasporeda</span><input type="hidden" name="filters[scope]" value="{{ $filters['scope'] }}"><input type="hidden" name="filters[group_by]" value="{{ $filters['group_by'] }}"><input type="hidden" name="filters[supplier_user_id]" value="{{ $filters['supplier_user_id'] }}"><label class="checkbox-row"><input type="checkbox" name="is_active" value="1" checked> Aktivan raspored</label><small class="muted">Koristi trenutni obuhvat i grupisanje. Period se automatski određuje pri slanju.</small></div><div class="span-4"><button class="button button-primary">Sačuvaj raspored</button></div></form></section>
<section class="panel form-section"><h2>Rasporedi</h2>@forelse($schedules as $schedule)<details class="analytics-schedule"><summary>{{ $schedule->name }} · {{ $schedule->is_active?'aktivan':'pauziran' }}</summary><div class="analytics-schedule-grid"><div><small>Učestalost</small><strong>{{ $schedule->frequency }} · {{ $schedule->send_time }}</strong></div><div><small>Sledeće slanje</small><strong>{{ $schedule->next_run_at?->format('d.m.Y H:i') ?? '—' }}</strong></div><div><small>Poslednje uspešno</small><strong>{{ $schedule->last_success_at?->format('d.m.Y H:i') ?? '—' }}</strong></div></div><p class="muted">{{ collect($schedule->recipients_json)->pluck('email')->implode(', ') }}</p><div class="button-row"><form method="post" action="{{ route('admin.report-schedules.run',$schedule) }}">@csrf<button class="button button-primary button-small">Pošalji sada</button></form><form method="post" action="{{ route('admin.report-schedules.toggle',$schedule) }}">@csrf @method('PATCH')<button class="button button-ghost button-small">{{ $schedule->is_active?'Pauziraj':'Aktiviraj' }}</button></form><form method="post" action="{{ route('admin.report-schedules.destroy',$schedule) }}" onsubmit="return confirm('Obrisati raspored?')">@csrf @method('DELETE')<button class="button button-danger button-small">Obriši</button></form></div></details>@empty<p class="muted">Još nema rasporeda.</p>@endforelse</section></div>
<section class="panel form-section"><h2>Poslednja slanja</h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Raspored</th><th>Primalac</th><th>Period</th><th>Status</th><th>Pokušaji</th><th>Poslato</th><th></th></tr></thead><tbody>@forelse($deliveries as $delivery)<tr><td>{{ $delivery->schedule?->name ?? 'Obrisan raspored' }}</td><td>{{ $delivery->recipient_email }}</td><td>{{ $delivery->period_from?->format('d.m.Y') }} – {{ $delivery->period_to?->format('d.m.Y') }}</td><td><span class="status-badge status-{{ $delivery->status==='sent'?'active':($delivery->status==='failed'?'archived':'draft') }}">{{ $delivery->status }}</span>@if($delivery->last_error)<small title="{{ $delivery->last_error }}">{{ \Illuminate\Support\Str::limit($delivery->last_error,80) }}</small>@endif</td><td>{{ $delivery->attempt_count }}</td><td>{{ $delivery->sent_at?->format('d.m.Y H:i') ?? '—' }}</td><td>@if(in_array($delivery->status,['failed','retry']))<form method="post" action="{{ route('admin.report-deliveries.retry',$delivery) }}">@csrf<button class="button button-ghost button-small">Ponovi</button></form>@endif</td></tr>@empty<tr><td colspan="7">Nema slanja.</td></tr>@endforelse</tbody></table></div></section>
@endcan

<section class="panel form-section"><div class="section-heading-row"><div><h2>Operativni izvozi</h2><p class="muted">Postojeći detaljni izvozi porudžbina, uplata i lagera ostaju dostupni.</p></div></div><div class="button-row">@can('reports.export')<a class="button button-ghost" href="{{ route('admin.reports.orders.csv',request()->query()) }}">Porudžbine CSV</a><a class="button button-ghost" target="_blank" href="{{ route('admin.reports.orders.pdf',request()->query()) }}">Porudžbine PDF</a><a class="button button-ghost" href="{{ route('admin.reports.payments.csv') }}">Uplate CSV</a>@endcan @can('inventory.export')<a class="button button-ghost" href="{{ route('admin.reports.inventory.csv') }}">Lager CSV</a>@endcan</div></section>
@endsection
