import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useMemo, useState } from 'react';
import { StyleSheet, Switch, Text, View } from 'react-native';

import { PageHeader } from '@/components/layout/page-header';
import { Screen } from '@/components/layout/screen';
import { useAppFeedback } from '@/components/ui/app-feedback';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { SelectSheet } from '@/components/ui/select-sheet';
import { ErrorState, LoadingState, UnavailableState } from '@/components/ui/states';
import { TextField } from '@/components/ui/text-field';
import { spacing, typography, type AppColors } from '@/constants/theme';
import { adminQueryKeys } from '@/features/admin/admin-query-keys';
import { apiAdminSystemSettings } from '@/features/admin/system-settings-admin-api';
import { useAuth } from '@/features/auth/auth-provider';
import { useAppTheme } from '@/theme/app-theme';

const FLAGS = [
  ['order_email_enabled','E-mail obaveštenja uključena'],['order_email_creation_enabled','Kreiranje porudžbine'],['order_email_updates_enabled','Izmene porudžbine'],['order_email_documents_enabled','Dokumenti'],['order_email_send_creator','Pošalji kreatoru'],['order_email_send_supplier','Pošalji odgovornom licu'],['order_email_custom_recipients_for_updates','Custom primaoci i za izmene'],['order_email_event_created','Event: kreirana'],['order_email_event_status','Event: status'],['order_email_event_tracking','Event: tracking'],['order_email_event_payment','Event: uplata'],['order_email_event_accepted','Event: preuzeta'],['order_email_event_reassigned','Event: dodeljena'],['order_email_event_deadlines','Event: rokovi'],['order_email_event_completed','Event: završena'],['order_email_event_reopened','Event: ponovo otvorena'],['order_email_event_document_cancelled','Event: storniran dokument'],['order_email_event_other','Ostali događaji'],['order_email_updates_attach_invoice','Priloži aktivni račun uz update'],['order_email_document_order_confirmation','Dokument: potvrda'],['order_email_document_proforma','Dokument: predračun'],['order_email_document_invoice','Dokument: račun'],['order_email_document_delivery_note','Dokument: otpremnica'],['product_email_new_items_enabled','Obaveštenje o novom artiklu'],
] as const;
const INTERVAL_KEYS = [['order_email_creation_interval_minutes','Kreiranje · interval'],['order_email_update_interval_minutes','Izmene · interval'],['order_email_document_interval_minutes','Dokumenti · interval'],['product_email_new_items_interval_minutes','Novi artikli · interval']] as const;

// MOBILE_V1_0_SYSTEM_SETTINGS_PARITY_BATCH37_SET08
export default function AdminOrderEmailSettingsScreen() {
  const { can, bootstrap } = useAuth(); const { colors: theme } = useAppTheme(); const styles = useMemo(() => createStyles(theme), [theme]); const feedback = useAppFeedback(); const client = useQueryClient(); const allowed = can('system.manage_settings');
  const query = useQuery({ queryKey: adminQueryKeys.systemSettingsOrderEmails(), queryFn: apiAdminSystemSettings.orderEmails.state, enabled: allowed });
  const [values, setValues] = useState<Record<string,string>>({}); useEffect(() => { if (query.data) setValues(query.data.data.settings); }, [query.data]);
  const save = useMutation({ mutationFn: () => apiAdminSystemSettings.orderEmails.update({ ...values, ...Object.fromEntries(FLAGS.map(([key]) => [key, values[key] === '1'])) }), onSuccess: (response) => { client.setQueryData(adminQueryKeys.systemSettingsOrderEmails(), response); feedback.notify({ tone: 'success', title: 'E-mail podešavanja su sačuvana' }); }, onError: (error) => feedback.notify({ tone: 'danger', title: 'Podešavanja nisu sačuvana', message: error instanceof Error ? error.message : 'Greška.' }) });
  const action = useMutation({ mutationFn: (kind: 'dispatch'|'retry') => kind === 'dispatch' ? apiAdminSystemSettings.orderEmails.dispatch() : apiAdminSystemSettings.orderEmails.retry(), onSuccess: (response) => { client.setQueryData(adminQueryKeys.systemSettingsOrderEmails(), response); feedback.notify({ tone: 'success', title: response.message ?? 'Outbox je ažuriran' }); }, onError: (error) => feedback.notify({ tone: 'danger', title: 'Outbox akcija nije uspela', message: error instanceof Error ? error.message : 'Greška.' }) });
  if (!allowed) return <UnavailableState title="E-mail podešavanja nisu dostupna" />; if (query.isLoading) return <LoadingState label="Učitavanje e-mail podešavanja…" />; if (query.isError || !query.data) return <ErrorState error={query.error} onRetry={() => void query.refetch()} />;
  const data = query.data.data; const set = (key:string,value:string) => setValues((current) => ({ ...current, [key]: value })); const intervalOptions = data.intervals.map((value) => ({ value: String(value), label: value === 0 ? 'Odmah' : `${value} min` }));
  return <Screen contentStyle={styles.content}><PageHeader title="E-mail porudžbina" eyebrow="Sistem · SET-08" name={bootstrap?.user.name} /><Card style={styles.card}><Text style={styles.title}>Outbox</Text><Text style={styles.meta}>Pending/retry {data.stats.pending} · Failed {data.stats.failed} · Poslato danas {data.stats.sent_today} · Schema {data.schema_ready ? 'READY' : 'NOT READY'}</Text><View style={styles.actions}><Button variant="secondary" loading={action.isPending} onPress={() => action.mutate('dispatch')}>Pošalji outbox sada</Button><Button variant="secondary" loading={action.isPending} onPress={() => action.mutate('retry')}>Ponovi sve failed poruke</Button></View></Card><Card style={styles.card}><Text style={styles.title}>Primaoci i intervali</Text><TextField label="Dodatni primaoci (razmak, zarez ili novi red)" value={values.order_email_custom_recipients ?? ''} onChangeText={(v) => set('order_email_custom_recipients', v)} autoCapitalize="none" />{INTERVAL_KEYS.map(([key,label]) => <SelectSheet key={key} label={label} value={values[key] ?? '0'} options={intervalOptions} onChange={(v) => set(key,v)} />)}</Card><Card style={styles.card}><Text style={styles.title}>Događaji i prilozi</Text>{FLAGS.map(([key,label]) => <View key={key} style={styles.row}><Text style={styles.body}>{label}</Text><Switch value={values[key] === '1'} onValueChange={(v) => set(key,v?'1':'0')} /></View>)}</Card><Button loading={save.isPending} onPress={() => save.mutate()}>Sačuvaj e-mail podešavanja</Button><Card style={styles.card}><Text style={styles.title}>Poslednje poruke</Text>{data.recent.slice(0,20).map((row) => <View key={row.id} style={styles.item}><Text style={styles.body}>{row.subject}</Text><Text style={styles.meta}>{row.recipient_email} · {row.event_type} · {row.status} · pokušaja {row.attempt_count}</Text>{row.last_error ? <Text style={styles.error}>{row.last_error}</Text> : null}</View>)}</Card></Screen>;
}
function createStyles(theme: AppColors) { return StyleSheet.create({ content: { gap: spacing.lg, paddingBottom: 160 }, card: { gap: spacing.md }, title: { ...typography.h2, color: theme.ink }, body: { ...typography.body, color: theme.ink, flex: 1 }, meta: { ...typography.small, color: theme.muted }, error: { ...typography.small, color: theme.danger }, row: { flexDirection:'row',alignItems:'center',gap:spacing.md }, actions:{gap:spacing.sm}, item:{gap:spacing.xs,paddingVertical:spacing.sm} }); }
