<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Release check profiles
    |--------------------------------------------------------------------------
    |
    | Profiles contain check keys from the checks registry below. The command
    | is intentionally non-destructive unless --repair is explicitly supplied.
    |
    */
    'profiles' => [
        'quick' => [
            'deployment',
            'auth',
            'reports',
            'customer_portal',
            'system_health',
        ],
        'standard' => [
            'deployment',
            'auth',
            'cache',
            'mail',
            'backup',
            'catalog_correlations',
            'catalog_ownership',
            'catalog_settings',
            'product_media',
            'smart_products',
            'cms_v214',
            'cms_v215',
            'cms_v216',
            'cms_v220',
            'orders',
            'order_create',
            'operations',
            'payments_inventory',
            'reports',
            'management_reports',
            'customer_portal',
            'after_sales',
            'field_operations',
            'service_parts',
            'warranties',
            'order_emails',
            'receivables',
            'automation',
            'system_health',
        ],
        'full' => [
            'deployment',
            'auth',
            'cache',
            'mail',
            'backup',
            'legacy',
            'legacy_media',
            'catalog_correlations',
            'catalog_ownership',
            'catalog_settings',
            'product_media',
            'smart_products',
            'cms_v214',
            'cms_v215',
            'cms_v216',
            'cms_v220',
            'orders',
            'order_create',
            'operations',
            'payments_inventory',
            'reports',
            'management_reports',
            'customer_portal',
            'after_sales',
            'field_operations',
            'service_parts',
            'warranties',
            'order_emails',
            'receivables',
            'automation',
            'detail_pages',
            'system_health',
        ],
        'rc' => [
            'deployment',
            'release_integrity',
            'security_hardening',
            'migrations',
            'access_control',
            'auth',
            'cache',
            'mail',
            'backup',
            'backup_verify',
            'legacy',
            'legacy_media',
            'catalog_correlations',
            'catalog_ownership',
            'catalog_settings',
            'product_media',
            'smart_products',
            'cms_v214',
            'cms_v215',
            'cms_v216',
            'cms_v220',
            'orders',
            'order_create',
            'operations',
            'payments_inventory',
            'reports',
            'management_reports',
            'customer_portal',
            'after_sales',
            'field_operations',
            'service_parts',
            'warranties',
            'order_emails',
            'receivables',
            'automation',
            'detail_pages',
            'system_health',
        ],
        'stable' => [
            'deployment',
            'release_integrity',
            'security_hardening',
            'migrations',
            'access_control',
            'auth',
            'cache',
            'mail',
            'backup',
            'backup_verify',
            'legacy',
            'legacy_media',
            'catalog_correlations',
            'catalog_ownership',
            'catalog_settings',
            'product_media',
            'smart_products',
            'cms_v214',
            'cms_v215',
            'cms_v216',
            'cms_v220',
            'orders',
            'order_create',
            'operations',
            'payments_inventory',
            'reports',
            'management_reports',
            'customer_portal',
            'after_sales',
            'field_operations',
            'service_parts',
            'warranties',
            'order_emails',
            'receivables',
            'automation',
            'detail_pages',
            'system_health',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Check registry
    |--------------------------------------------------------------------------
    |
    | base arguments always apply. repair/render/strict arguments are merged
    | only when the corresponding app:release-check option is supplied.
    |
    */
    'checks' => [
        'release_integrity' => [
            'label' => 'Integritet release paketa',
            'group' => 'Release hardening',
            'command' => 'app:release-integrity',
        ],
        'security_hardening' => [
            'label' => 'Bezbednosni hardening',
            'group' => 'Release hardening',
            'command' => 'app:security-hardening-doctor',
        ],
        'migrations' => [
            'label' => 'Migration i DB runtime audit',
            'group' => 'Release hardening',
            'command' => 'app:migrations-doctor',
            'strict' => ['--strict' => true],
        ],
        'access_control' => [
            'label' => 'Role, permission i route audit',
            'group' => 'Release hardening',
            'command' => 'app:access-control-doctor',
        ],
        'backup_verify' => [
            'label' => 'Integritet poslednjeg backupa',
            'group' => 'Release hardening',
            'command' => 'app:backup-verify',
        ],
        'deployment' => [
            'label' => 'Produkcioni deployment',
            'group' => 'Platforma',
            'command' => 'app:deployment-check',
            'repair' => ['--repair' => true],
            'strict' => ['--strict-legacy-grants' => true],
        ],
        'system_health' => [
            'label' => 'Zdravlje sistema',
            'group' => 'Platforma',
            'command' => 'app:system-health',
            'snapshot' => ['--snapshot' => true],
        ],
        'auth' => [
            'label' => 'Prijava i Dashboard',
            'group' => 'Platforma',
            'command' => 'app:auth-doctor',
            'render' => ['--render-dashboard' => true],
        ],
        'cache' => [
            'label' => 'Cache runtime',
            'group' => 'Platforma',
            'command' => 'app:cache-doctor',
        ],
        'mail' => [
            'label' => 'E-mail konfiguracija',
            'group' => 'Platforma',
            'command' => 'app:mail-doctor',
        ],
        'backup' => [
            'label' => 'Backup infrastruktura',
            'group' => 'Platforma',
            'command' => 'app:backup-doctor',
        ],
        'legacy' => [
            'label' => 'Legacy read-only konekcija',
            'group' => 'Platforma',
            'command' => 'legacy:check',
            'strict' => ['--strict-grants' => true],
        ],
        'legacy_media' => [
            'label' => 'Legacy medijski fajlovi',
            'group' => 'Platforma',
            'command' => 'legacy:media-check',
            'base' => ['--limit' => 20],
        ],
        'catalog_correlations' => [
            'label' => 'Korelisani katalog',
            'group' => 'Katalog',
            'command' => 'app:catalog-correlations-doctor',
        ],
        'catalog_ownership' => [
            'label' => 'Jedinstveni katalog i vlasništvo artikala',
            'group' => 'Katalog',
            'command' => 'app:catalog-ownership-doctor',
            'render' => ['--render' => true],
        ],
        'catalog_settings' => [
            'label' => 'Tipovi proizvoda, kategorije i specifikacije',
            'group' => 'Katalog',
            'command' => 'app:catalog-settings-doctor',
            'repair' => ['--repair' => true],
        ],
        'product_media' => [
            'label' => 'Galerija, upload i obrada slika artikala',
            'group' => 'Katalog',
            'command' => 'app:product-media-doctor',
        ],
        'smart_products' => [
            'label' => 'Pametno upravljanje artiklima',
            'group' => 'Katalog',
            'command' => 'app:smart-products-doctor',
            'repair' => ['--repair' => true],
        ],
        'cms_v214' => [
            'label' => 'v2.1.4 dugmad, model i životni ciklus artikla',
            'group' => 'Katalog',
            'command' => 'app:cms-v2-1-4-doctor',
            'repair' => ['--repair' => true],
        ],
        'cms_v215' => [
            'label' => 'v2.1.5 UX, mobilni prikaz, runtime i specifikacije računara',
            'group' => 'Platforma',
            'command' => 'app:cms-v2-1-5-doctor',
            'render' => ['--render' => true],
            'repair' => ['--repair' => true],
        ],
        'cms_v216' => [
            'label' => 'v2.1.6 performanse i kvalitet podataka',
            'group' => 'Platforma',
            'command' => 'app:cms-v2-1-6-doctor',
            'render' => ['--render' => true],
            'repair' => ['--repair' => true],
            'strict' => ['--strict' => true],
        ],
        'cms_v220' => [
            'label' => 'v2.2.0 Mobile API Foundation',
            'group' => 'Platforma',
            'command' => 'app:cms-v2-2-0-doctor',
            'strict' => ['--strict' => true],
        ],
        'orders' => [
            'label' => 'Porudžbine',
            'group' => 'Prodaja',
            'command' => 'app:orders-doctor',
            'render' => ['--render' => true],
        ],
        'order_create' => [
            'label' => 'Kreiranje porudžbine',
            'group' => 'Prodaja',
            'command' => 'app:order-create-doctor',
            'render' => ['--render' => true],
        ],
        'operations' => [
            'label' => 'Operacije i provizije',
            'group' => 'Prodaja',
            'command' => 'app:operations-doctor',
            'render' => ['--render' => true],
        ],
        'payments_inventory' => [
            'label' => 'Uplate i lager',
            'group' => 'Prodaja',
            'command' => 'app:payments-inventory-doctor',
            'render' => ['--render' => true],
        ],
        'reports' => [
            'label' => 'Operativni izveštaji',
            'group' => 'Izveštaji',
            'command' => 'app:reports-doctor',
            'render' => ['--render' => true],
        ],
        'management_reports' => [
            'label' => 'Profitabilnost i upravljački izveštaji',
            'group' => 'Izveštaji',
            'command' => 'app:management-reports-doctor',
            'repair' => ['--repair' => true],
            'render' => ['--render' => true],
        ],
        'customer_portal' => [
            'label' => 'Customer Portal 2.0',
            'group' => 'Korisnici',
            'command' => 'app:customer-portal-doctor',
            'render' => ['--render' => true],
        ],
        'after_sales' => [
            'label' => 'Reklamacije i postprodaja',
            'group' => 'Postprodaja',
            'command' => 'app:after-sales-doctor',
        ],
        'field_operations' => [
            'label' => 'Terenske operacije',
            'group' => 'Postprodaja',
            'command' => 'app:field-operations-doctor',
        ],
        'service_parts' => [
            'label' => 'Servisni delovi',
            'group' => 'Postprodaja',
            'command' => 'app:service-parts-doctor',
        ],
        'warranties' => [
            'label' => 'Garancije',
            'group' => 'Postprodaja',
            'command' => 'app:warranties-doctor',
        ],
        'order_emails' => [
            'label' => 'Outbox e-mailova porudžbina',
            'group' => 'Automatizacija',
            'command' => 'app:order-emails-doctor',
        ],
        'receivables' => [
            'label' => 'Potraživanja',
            'group' => 'Automatizacija',
            'command' => 'app:receivables-doctor',
        ],
        'automation' => [
            'label' => 'Operativna automatizacija',
            'group' => 'Automatizacija',
            'command' => 'app:automation-doctor',
        ],
        'detail_pages' => [
            'label' => 'Regresija detaljnih stranica',
            'group' => 'Render',
            'command' => 'app:detail-pages-doctor',
            'requires_render' => true,
        ],
    ],

    'report_directory' => 'release-check',
    'report_output_limit' => 30000,
];
