@extends('layouts.app')
@section('title', 'Servisni lager')
@section('content')
<div class="page-heading"><div><span class="eyebrow">Rezervni delovi</span><h1>Servisni lager</h1><p>Stanje, rezervacije, utrošak i korekcije delova za terenske radne naloge.</p></div><div class="header-button-row">@can('service_parts.procurement')<a class="button button-ghost" href="{{ route('admin.service-part-suppliers.index') }}">Dobavljači</a><a class="button button-primary" href="{{ route('admin.service-part-purchases.index') }}">Nabavke</a>@endcan</div></div>
<div class="stats-grid four-cards"><article class="stat-card"><span>Aktivni delovi</span><strong>{{ $stats['active'] }}</strong></article><article class="stat-card warning"><span>Nizak lager</span><strong>{{ $stats['low'] }}</strong></article><article class="stat-card info"><span>Sa rezervacijama</span><strong>{{ $stats['reserved_lines'] }}</strong></article><article class="stat-card"><span>Vrednost lagera</span><strong>{{ number_format($stats['value'],2,',','.') }} RSD</strong></article></div>
<div class="settings-grid service-parts-grid">
<section class="panel form-section"><h2>Novi rezervni deo</h2><form method="post" action="{{ route('admin.service-parts.store') }}" class="form-grid two-columns">@csrf
<label><span>Šifra / SKU</span><input name="sku" required maxlength="80" value="{{ old('sku') }}"></label><label><span>Naziv</span><input name="name" required maxlength="190" value="{{ old('name') }}"></label>
<label><span>Jedinica mere</span><input name="unit" required maxlength="30" value="{{ old('unit','kom') }}"></label><label><span>Početno stanje</span><input type="number" name="stock_quantity" min="0" step="0.001" value="{{ old('stock_quantity',0) }}"></label>
<label><span>Minimalno stanje</span><input type="number" name="minimum_quantity" min="0" step="0.001" value="{{ old('minimum_quantity',0) }}"></label><label><span>Prosečna cena RSD</span><input type="number" name="average_cost_rsd" min="0" step="0.01" value="{{ old('average_cost_rsd',0) }}"></label>
<label><span>Preferirani dobavljač</span><select name="preferred_supplier_id"><option value="">Bez dobavljača</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select></label><label class="checkbox-row"><input type="checkbox" name="is_active" value="1" checked><span>Aktivan deo</span></label>
<label class="full-width"><span>Napomena</span><textarea name="notes" maxlength="5000">{{ old('notes') }}</textarea></label><button class="button button-primary full-width" type="submit">Kreiraj deo</button></form></section>
<section class="panel form-section"><h2>Pretraga i filteri</h2><form method="get" class="form-grid"><label><span>Šifra ili naziv</span><input name="q" value="{{ $q }}"></label><label><span>Prikaz</span><select name="filter"><option value="all" @selected($filter==='all')>Svi aktivni</option><option value="low" @selected($filter==='low')>Nizak lager</option><option value="available" @selected($filter==='available')>Raspoloživi</option><option value="inactive" @selected($filter==='inactive')>Neaktivni</option></select></label><button class="button button-ghost" type="submit">Primeni</button></form><div class="alpha-note">Raspoloživo = fizičko stanje minus količina rezervisana za aktivne radne naloge.</div></section>
</div>
<section class="panel form-section"><h2>Delovi</h2><div class="table-wrap"><table><thead><tr><th>Deo</th><th>Stanje</th><th>Rezervisano</th><th>Raspoloživo</th><th>Minimum</th><th>Dobavljač</th><th>Izmena</th></tr></thead><tbody>@forelse($parts as $part)<tr class="{{ $part->isLowStock()?'row-warning':'' }}"><td><strong>{{ $part->name }}</strong><small>{{ $part->sku }} · {{ $part->unit }}</small></td><td>{{ number_format((float)$part->stock_quantity,3,',','.') }}</td><td>{{ number_format((float)$part->reserved_quantity,3,',','.') }}</td><td><strong>{{ number_format($part->availableQuantity(),3,',','.') }}</strong></td><td>{{ number_format((float)$part->minimum_quantity,3,',','.') }}</td><td>{{ $part->preferredSupplier?->name ?? '—' }}</td><td><details><summary class="button button-ghost button-small">Uredi</summary><div class="details-popover"><form method="post" action="{{ route('admin.service-parts.update',$part) }}" class="form-grid">@csrf @method('PUT')<input name="sku" value="{{ $part->sku }}" required><input name="name" value="{{ $part->name }}" required><input name="unit" value="{{ $part->unit }}" required><input type="number" step="0.001" min="0" name="minimum_quantity" value="{{ $part->minimum_quantity }}"><input type="number" step="0.01" min="0" name="average_cost_rsd" value="{{ $part->average_cost_rsd }}"><select name="preferred_supplier_id"><option value="">Bez dobavljača</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected($part->preferred_supplier_id===$supplier->id)>{{ $supplier->name }}</option>@endforeach</select><textarea name="notes">{{ $part->notes }}</textarea><label class="checkbox-row"><input type="checkbox" name="is_active" value="1" @checked($part->is_active)><span>Aktivan</span></label><button class="button button-primary" type="submit">Sačuvaj</button></form><hr><form method="post" action="{{ route('admin.service-parts.adjust',$part) }}" class="form-grid">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><label><span>Korekcija (+/-)</span><input type="number" name="quantity_change" step="0.001" required></label><label><span>Razlog</span><textarea name="note" required minlength="5"></textarea></label><button class="button button-ghost" type="submit">Knjiži korekciju</button></form></div></details></td></tr>@empty<tr><td colspan="7">Nema rezervnih delova za izabrani filter.</td></tr>@endforelse</tbody></table></div>{{ $parts->links() }}</section>
<section class="panel form-section"><h2>Poslednja kretanja</h2><div class="table-wrap"><table><thead><tr><th>Datum</th><th>Deo</th><th>Vrsta</th><th>Stanje</th><th>Rezervacija</th><th>Radni nalog</th></tr></thead><tbody>@forelse($movements as $movement)<tr><td>{{ $movement->created_at?->format('d.m.Y H:i') }}</td><td>{{ $movement->part?->name }}<small>{{ $movement->part?->sku }}</small></td><td>{{ $movement->movement_type }}</td><td>{{ number_format((float)$movement->stock_change,3,',','.') }}</td><td>{{ number_format((float)$movement->reserved_change,3,',','.') }}</td><td>@if($movement->workOrder)<a href="{{ route('admin.field-operations.show',$movement->workOrder) }}">{{ $movement->workOrder->work_order_number }}</a>@else—@endif</td></tr>@empty<tr><td colspan="6">Još nema kretanja.</td></tr>@endforelse</tbody></table></div></section>
@endsection
