@extends('layouts.app')
@section('title', 'Nabavka rezervnih delova')
@section('content')
<a class="back-link" href="{{ route('admin.service-parts.index') }}">← Servisni lager</a><div class="page-heading"><div><span class="eyebrow">Nabavka</span><h1>Zahtevi za nabavku</h1><p>Od nacrta do prijema delova na servisni lager.</p></div><a class="button button-ghost" href="{{ route('admin.service-part-suppliers.index') }}">Dobavljači</a></div>
<div class="settings-grid"><section class="panel form-section"><h2>Novi zahtev</h2><form method="post" action="{{ route('admin.service-part-purchases.store') }}" class="form-grid" data-purchase-form>@csrf<label><span>Dobavljač</span><select name="supplier_id"><option value="">Odredi kasnije</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select></label><label><span>Očekivani datum</span><input type="date" name="expected_at"></label><label><span>Referenca dobavljača</span><input name="supplier_reference"></label><label><span>Napomena</span><textarea name="notes"></textarea></label><div class="full-width"><div class="section-heading-row"><h3>Stavke</h3><button class="button button-ghost button-small" type="button" data-add-purchase-item>+ Dodaj stavku</button></div><div data-purchase-items></div></div><button class="button button-primary full-width" type="submit">Kreiraj nacrt nabavke</button></form></section><section class="panel form-section"><h2>Filteri</h2><form method="get" class="form-grid"><input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Broj, referenca ili dobavljač"><select name="status"><option value="">Svi statusi</option>@foreach($statuses as $key=>$label)<option value="{{ $key }}" @selected(($filters['status'] ?? '')===$key)>{{ $label }}</option>@endforeach</select><button class="button button-ghost">Primeni</button></form></section></div>
<section class="panel form-section"><h2>Istorija nabavki</h2><div class="table-wrap"><table><thead><tr><th>Broj</th><th>Dobavljač</th><th>Status</th><th>Stavke</th><th>Vrednost</th><th>Očekivano</th><th></th></tr></thead><tbody>@forelse($purchaseRequests as $purchase)<tr><td><strong>{{ $purchase->request_number }}</strong><small>{{ $purchase->created_at?->format('d.m.Y H:i') }}</small></td><td>{{ $purchase->supplier?->name ?? 'Nije određen' }}</td><td><span class="status-badge">{{ $statuses[$purchase->status] ?? $purchase->status }}</span></td><td>{{ $purchase->items->count() }}</td><td>{{ number_format((float)$purchase->total_cost_rsd,2,',','.') }} RSD</td><td>{{ $purchase->expected_at?->format('d.m.Y') ?? '—' }}</td><td><a class="button button-ghost button-small" href="{{ route('admin.service-part-purchases.show',$purchase) }}">Otvori</a></td></tr>@empty<tr><td colspan="7">Nema zahteva za nabavku.</td></tr>@endforelse</tbody></table></div>{{ $purchaseRequests->links() }}</section>
<template data-purchase-item-template><div class="purchase-item-row"><select name="items[__INDEX__][service_part_id]" required><option value="">Izaberi deo</option>@foreach($parts as $part)<option value="{{ $part->id }}">{{ $part->sku }} · {{ $part->name }}</option>@endforeach</select><input type="number" name="items[__INDEX__][ordered_quantity]" min="0.001" step="0.001" placeholder="Količina" required><input type="number" name="items[__INDEX__][unit_cost_rsd]" min="0" step="0.01" placeholder="Cena RSD"><button type="button" class="button button-danger button-small" data-remove-purchase-item>×</button></div></template>
@endsection
@push('scripts')<script>(()=>{const box=document.querySelector('[data-purchase-items]');const tpl=document.querySelector('[data-purchase-item-template]');let i=0;const add=()=>{const wrap=document.createElement('div');wrap.innerHTML=tpl.innerHTML.replaceAll('__INDEX__',String(i++));const row=wrap.firstElementChild;row.querySelector('[data-remove-purchase-item]').addEventListener('click',()=>{if(box.children.length>1)row.remove();});box.appendChild(row);};document.querySelector('[data-add-purchase-item]')?.addEventListener('click',add);add();})();</script>@endpush
