import type { AdminModuleKey } from '@/features/admin/admin-api';

export const adminQueryKeys = {
  all: ['admin'] as const,
  foundation: () => ['admin', 'foundation'] as const,
  module: (module: AdminModuleKey) => ['admin', module] as const,
  commissions: () => ['admin', 'commissions'] as const,
  commissionsList: (params: unknown) => ['admin', 'commissions', 'list', params] as const,
  commission: (id: number) => ['admin', 'commissions', 'detail', id] as const,
  warranties: () => ['admin', 'warranties'] as const,
  warrantiesList: (params: unknown) => ['admin', 'warranties', 'list', params] as const,
  warranty: (id: number) => ['admin', 'warranties', 'detail', id] as const,
  warrantyRules: () => ['admin', 'warranties', 'rules'] as const,
  reports: () => ['admin', 'reports'] as const,
  managementReport: (params: unknown) => ['admin', 'reports', 'management', params] as const,
  reportSchedules: () => ['admin', 'reports', 'schedules'] as const,
  systemHealth: () => ['admin', 'system-health'] as const,
  auditEvents: (params: unknown) => ['admin', 'audit-events', params] as const,
  auditEvent: (eventId: number) => ['admin', 'audit-events', eventId] as const,
  adminOrders: (params: unknown) => ['admin', 'orders', params] as const,
  adminOrder: (orderId: number) => ['admin', 'orders', orderId] as const,
  afterSalesAdmin: () => ['admin', 'after-sales'] as const,
  afterSalesAdminList: (params: unknown) => ['admin', 'after-sales', 'list', params] as const,
  afterSalesAdminCase: (caseId: number) => ['admin', 'after-sales', 'detail', caseId] as const,
  fieldOperations: () => ['admin', 'field-operations'] as const,
  fieldOperationsList: (params: unknown) => ['admin', 'field-operations', 'list', params] as const,
  fieldWorkOrder: (workOrderId: number) => ['admin', 'field-operations', 'detail', workOrderId] as const,
  receivables: () => ['admin', 'receivables'] as const,
  receivablesList: (params: unknown) => ['admin', 'receivables', 'list', params] as const,
  receivable: (receivableId: number) => ['admin', 'receivables', 'detail', receivableId] as const,
  serviceParts: () => ['admin', 'service-parts'] as const,
  servicePartsList: (params: unknown) => ['admin', 'service-parts', 'list', params] as const,
  servicePartSuppliersRoot: () => ['admin', 'service-part-suppliers'] as const,
  servicePartSuppliers: (params: unknown) => ['admin', 'service-part-suppliers', 'list', params] as const,
  servicePartPurchasesRoot: () => ['admin', 'service-part-purchases'] as const,
  servicePartPurchases: (params: unknown) => ['admin', 'service-part-purchases', 'list', params] as const,
  servicePartPurchase: (purchaseId: number) => ['admin', 'service-part-purchases', 'detail', purchaseId] as const,
  inventory: () => ['admin', 'inventory'] as const,
  inventoryList: (params: unknown) => ['admin', 'inventory', 'list', params] as const,
  inventoryLookup: (q: string) => ['admin', 'inventory', 'lookup', q] as const,
  inventoryMovements: (params: unknown) => ['admin', 'inventory', 'movements', params] as const,
};
