import type { AdminModuleKey } from '@/features/admin/admin-api';

export const adminQueryKeys = {
  all: ['admin'] as const,
  foundation: () => ['admin', 'foundation'] as const,
  module: (module: AdminModuleKey) => ['admin', module] as const,
  commissions: () => ['admin', 'commissions'] as const,
  commissionsList: (params: unknown) => ['admin', 'commissions', 'list', params] as const,
  commission: (id: number) => ['admin', 'commissions', 'detail', id] as const,
  warranties: () => ['admin', 'warranties'] as const,
  warrantiesList: (params: unknown) => ['admin', 'warranties', 'list', params] as const,
  warranty: (id: number) => ['admin', 'warranties', 'detail', id] as const,
  warrantyRules: () => ['admin', 'warranties', 'rules'] as const,
  reports: () => ['admin', 'reports'] as const,
  managementReport: (params: unknown) => ['admin', 'reports', 'management', params] as const,
  reportSchedules: () => ['admin', 'reports', 'schedules'] as const,
  systemHealth: () => ['admin', 'system-health'] as const,
  auditEvents: (params: unknown) => ['admin', 'audit-events', params] as const,
  auditEvent: (eventId: number) => ['admin', 'audit-events', eventId] as const,
  adminOrders: (params: unknown) => ['admin', 'orders', params] as const,
  adminOrder: (orderId: number) => ['admin', 'orders', orderId] as const,
  afterSalesAdmin: () => ['admin', 'after-sales'] as const,
  afterSalesAdminList: (params: unknown) => ['admin', 'after-sales', 'list', params] as const,
  afterSalesAdminCase: (caseId: number) => ['admin', 'after-sales', 'detail', caseId] as const,
  fieldOperations: () => ['admin', 'field-operations'] as const,
  fieldOperationsList: (params: unknown) => ['admin', 'field-operations', 'list', params] as const,
  fieldWorkOrder: (workOrderId: number) => ['admin', 'field-operations', 'detail', workOrderId] as const,
  receivables: () => ['admin', 'receivables'] as const,
  receivablesList: (params: unknown) => ['admin', 'receivables', 'list', params] as const,
  receivable: (receivableId: number) => ['admin', 'receivables', 'detail', receivableId] as const,
  serviceParts: () => ['admin', 'service-parts'] as const,
  servicePartsList: (params: unknown) => ['admin', 'service-parts', 'list', params] as const,
  servicePartSuppliersRoot: () => ['admin', 'service-part-suppliers'] as const,
  servicePartSuppliers: (params: unknown) => ['admin', 'service-part-suppliers', 'list', params] as const,
  servicePartPurchasesRoot: () => ['admin', 'service-part-purchases'] as const,
  servicePartPurchases: (params: unknown) => ['admin', 'service-part-purchases', 'list', params] as const,
  servicePartPurchase: (purchaseId: number) => ['admin', 'service-part-purchases', 'detail', purchaseId] as const,
  inventory: () => ['admin', 'inventory'] as const,
  inventoryList: (params: unknown) => ['admin', 'inventory', 'list', params] as const,
  inventoryLookup: (q: string) => ['admin', 'inventory', 'lookup', q] as const,
  inventoryMovements: (params: unknown) => ['admin', 'inventory', 'movements', params] as const,
  // MOBILE_V0_8_COMPLETE_USER_MANAGEMENT_BATCH12
  users: () => ['admin', 'users'] as const,
  usersList: (params: unknown) => ['admin', 'users', 'list', params] as const,
  user: (userId: number) => ['admin', 'users', 'detail', userId] as const,
  userOptions: () => ['admin', 'users', 'options'] as const,
  // MOBILE_V1_0_CUSTOMER_PORTAL_PARITY_BATCH33
  customerPortalRoot: () => ['admin', 'customer-portal'] as const,
  customerPortal: (params: unknown) => ['admin', 'customer-portal', 'list', params] as const,
  customerPortalUserRoot: (userId: number) => ['admin', 'customer-portal', 'user', userId] as const,
  customerPortalUser: (userId: number, orderQ: string) => ['admin', 'customer-portal', 'user', userId, orderQ] as const,
  customerPortalConversation: (conversationId: number) => ['admin', 'customer-portal', 'conversation', conversationId] as const,
  // MOBILE_V1_0_SET_01_MODULE_SETTINGS_PARITY_BATCH30
  moduleSettings: () => ['admin', 'settings', 'modules'] as const,
  // MOBILE_V0_8_EUR_RSD_EXCHANGE_RATE_BATCH13
  exchangeRate: () => ['admin', 'exchange-rate'] as const,
  // MOBILE_V1_0_ADMIN_PURCHASE_COST_PARITY_BATCH19_V4
  purchaseCosts: (showAll: boolean) => ['admin', 'catalog', 'purchase-costs', showAll] as const,
  // MOBILE_V0_9_GLOBAL_BRAND_MANAGER_BATCH3
  brands: () => ['admin', 'brands'] as const,
  brandsList: (params: unknown) => ['admin', 'brands', 'list', params] as const,
  brandOptions: () => ['admin', 'brands', 'options'] as const,
  // MOBILE_V1_0_ADMIN_CATALOG_DICTIONARIES_BATCH22
  dictionaries: () => ['admin', 'catalog', 'dictionaries'] as const,
  dictionary: (resource: string) => ['admin', 'catalog', 'dictionaries', resource] as const,
  dictionaryProductType: (id: number) => ['admin', 'catalog', 'dictionaries', 'product-types', id] as const,
};
