@extends('layouts.app')
@section('title', 'Garancije')
@section('content')
<div class="page-heading"><div><span class="eyebrow">Postprodaja</span><h1>Garancije i preventivno održavanje</h1><p>Pravila, garantni listovi, serijski brojevi i planirani servisni intervali.</p></div><div class="header-button-row"><form method="post" action="{{ route('admin.warranties.backfill') }}">@csrf<button class="button button-ghost" type="submit">Generiši nedostajuće garancije</button></form></div></div>
<div class="stats-grid four-cards"><article class="stat-card"><span>Aktivne garancije</span><strong>{{ $stats['active'] }}</strong></article><article class="stat-card warning"><span>Ističu za 30 dana</span><strong>{{ $stats['expiring'] }}</strong></article><article class="stat-card info"><span>Održavanje uskoro</span><strong>{{ $stats['maintenance_due'] }}</strong></article><article class="stat-card"><span>Poništene</span><strong>{{ $stats['void'] }}</strong></article></div>
<div class="settings-grid">
<section class="panel form-section"><h2>Novo pravilo garancije</h2><form method="post" action="{{ route('admin.warranties.rules.store') }}" class="form-grid two-columns">@csrf
<label class="full-width"><span>Naziv pravila</span><input name="name" required maxlength="190" value="{{ old('name') }}"></label>
<label><span>Obuhvat</span><select name="scope_type" data-warranty-scope><option value="global">Svi proizvodi</option><option value="category">Kategorija</option><option value="product">Pojedinačni proizvod</option></select></label>
<label><span>Prioritet</span><input type="number" name="priority" min="-1000" max="1000" value="{{ old('priority',0) }}"></label>
<label data-warranty-category hidden><span>Kategorija</span><select name="category_id"><option value="">Izaberi kategoriju</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label>
<label data-warranty-product hidden><span>Proizvod</span><select name="product_id"><option value="">Izaberi proizvod</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->sku }} · {{ $product->name }}</option>@endforeach</select></label>
<label><span>Trajanje (meseci)</span><input type="number" name="duration_months" min="0" max="240" value="{{ old('duration_months',24) }}" required></label><label><span>Dodatni dani</span><input type="number" name="duration_days" min="0" max="3650" value="{{ old('duration_days',0) }}" required></label>
<label><span>Preventivni interval (meseci)</span><input type="number" name="maintenance_interval_months" min="1" max="120" value="{{ old('maintenance_interval_months') }}" placeholder="Bez intervala"></label>
<label class="full-width"><span>Uslovi garancije</span><textarea name="terms" maxlength="20000">{{ old('terms') }}</textarea></label>
<label class="checkbox-row full-width"><input type="checkbox" name="is_active" value="1" checked><span>Pravilo je aktivno</span></label>
<button class="button button-primary full-width" type="submit">Sačuvaj pravilo</button></form></section>
<section class="panel form-section"><h2>Filter garantnih listova</h2><form method="get" class="form-grid"><label><span>Broj, porudžbina, SKU ili naziv</span><input name="q" value="{{ $filters['q'] ?? '' }}"></label><label><span>Status</span><select name="status"><option value="">Svi</option><option value="active" @selected(($filters['status']??'')==='active')>Aktivne</option><option value="expired" @selected(($filters['status']??'')==='expired')>Istekle</option><option value="void" @selected(($filters['status']??'')==='void')>Poništene</option></select></label><label><span>Održavanje</span><select name="maintenance"><option value="">Sve</option><option value="due" @selected(($filters['maintenance']??'')==='due')>Ima sledeći termin</option><option value="scheduled" @selected(($filters['maintenance']??'')==='scheduled')>Zakazano</option><option value="overdue" @selected(($filters['maintenance']??'')==='overdue')>Kasni</option></select></label><button class="button button-ghost" type="submit">Primeni</button></form><div class="alpha-note">Specifično pravilo proizvoda ima prednost nad pravilom kategorije, a pravilo kategorije nad globalnim.</div></section>
</div>
<section class="panel form-section"><h2>Pravila</h2><div class="table-wrap"><table><thead><tr><th>Pravilo</th><th>Obuhvat</th><th>Trajanje</th><th>Održavanje</th><th>Status</th><th>Izmena</th></tr></thead><tbody>@foreach($rules as $rule)<tr><td><strong>{{ $rule->name }}</strong><small>Prioritet {{ $rule->priority }}</small></td><td>{{ $rule->scope_type==='product' ? ($rule->product?->name ?? 'Obrisan proizvod') : ($rule->scope_type==='category' ? ($rule->category?->name ?? 'Obrisana kategorija') : 'Svi proizvodi') }}</td><td>{{ $rule->duration_months ? $rule->duration_months.' mes.' : '' }}{{ $rule->duration_months && $rule->duration_days ? ' + ' : '' }}{{ $rule->duration_days ? $rule->duration_days.' dana' : '' }}</td><td>{{ $rule->maintenance_interval_months ? $rule->maintenance_interval_months.' mes.' : 'Nije obavezno' }}</td><td><span class="status-badge status-{{ $rule->is_active?'active':'archived' }}">{{ $rule->is_active?'Aktivno':'Neaktivno' }}</span></td><td><details><summary class="button button-ghost button-small">Uredi</summary><div class="details-popover"><form method="post" action="{{ route('admin.warranties.rules.update',$rule) }}" class="form-grid">@csrf @method('PUT')<input name="name" value="{{ $rule->name }}" required><select name="scope_type"><option value="global" @selected($rule->scope_type==='global')>Svi proizvodi</option><option value="category" @selected($rule->scope_type==='category')>Kategorija</option><option value="product" @selected($rule->scope_type==='product')>Proizvod</option></select><select name="category_id"><option value="">Bez kategorije</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($rule->category_id===$category->id)>{{ $category->name }}</option>@endforeach</select><select name="product_id"><option value="">Bez proizvoda</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected($rule->product_id===$product->id)>{{ $product->sku }} · {{ $product->name }}</option>@endforeach</select><input type="number" name="duration_months" min="0" max="240" value="{{ $rule->duration_months }}" required><input type="number" name="duration_days" min="0" max="3650" value="{{ $rule->duration_days ?? 0 }}" required><input type="number" name="maintenance_interval_months" min="1" max="120" value="{{ $rule->maintenance_interval_months }}" placeholder="Bez intervala"><input type="number" name="priority" min="-1000" max="1000" value="{{ $rule->priority }}"><textarea name="terms">{{ $rule->terms }}</textarea><label class="checkbox-row"><input type="checkbox" name="is_active" value="1" @checked($rule->is_active)><span>Aktivno</span></label><button class="button button-primary" type="submit">Sačuvaj</button></form></div></details></td></tr>@endforeach</tbody></table></div></section>
<section class="panel form-section"><h2>Garantni listovi</h2><div class="table-wrap"><table><thead><tr><th>Broj</th><th>Porudžbina</th><th>Kupac</th><th>Proizvod</th><th>Važi do</th><th>Status</th><th></th></tr></thead><tbody>@forelse($warranties as $warranty)@php($status=$warranty->effectiveStatus())<tr><td><strong>{{ $warranty->warranty_number }}</strong></td><td>{{ $warranty->order?->order_number }}</td><td>{{ $warranty->customer_name_snapshot }}</td><td>{{ $warranty->product_name_snapshot }}<small>{{ $warranty->product_sku_snapshot }}</small></td><td>{{ $warranty->expires_at?->format('d.m.Y') }}@if($warranty->next_maintenance_at)<small>Sledeći servis: {{ $warranty->next_maintenance_at->format('d.m.Y') }}</small>@endif</td><td><span class="status-badge status-{{ $status==='active'?'active':($status==='expired'?'draft':'archived') }}">{{ ['active'=>'Aktivna','expired'=>'Istekla','void'=>'Poništena'][$status] }}</span></td><td><a class="button button-ghost button-small" href="{{ route('admin.warranties.show',$warranty) }}">Otvori</a></td></tr>@empty<tr><td colspan="7">Nema garantnih listova za izabrani filter.</td></tr>@endforelse</tbody></table></div>{{ $warranties->links() }}</section>
@push('scripts')<script>document.querySelectorAll('[data-warranty-scope]').forEach((s)=>{const sync=()=>{const f=s.closest('form');f.querySelector('[data-warranty-category]').hidden=s.value!=='category';f.querySelector('[data-warranty-product]').hidden=s.value!=='product'};s.addEventListener('change',sync);sync()});</script>@endpush
@endsection
