@extends('layouts.app')
@section('title', $warranty->warranty_number)
@section('content')
@php($status=$warranty->effectiveStatus())
<div class="page-heading"><div><span class="eyebrow">Garantni list</span><h1>{{ $warranty->warranty_number }}</h1><p>{{ $warranty->product_name_snapshot }} · Porudžbina {{ $warranty->order?->order_number }}</p></div><div class="header-button-row"><a class="button button-ghost" target="_blank" href="{{ route('warranties.pdf',$warranty) }}">Otvori PDF</a><a class="button button-ghost" href="{{ route('admin.warranties.index') }}">Nazad</a></div></div>
<div class="details-layout"><div class="details-main">
<section class="panel form-section"><div class="card-header-row"><div><h2>Podaci garancije</h2><p class="muted">Snapshot kupca i proizvoda ostaje nepromenjen u odnosu na trenutak izdavanja.</p></div><span class="status-badge status-{{ $status==='active'?'active':($status==='expired'?'draft':'archived') }}">{{ ['active'=>'Aktivna','expired'=>'Istekla','void'=>'Poništena'][$status] }}</span></div><dl class="detail-list"><dt>Kupac</dt><dd>{{ $warranty->customer_name_snapshot }}</dd><dt>Adresa</dt><dd>{{ $warranty->customer_address_snapshot }}, {{ $warranty->customer_postal_code_snapshot }} {{ $warranty->customer_city_snapshot }}</dd><dt>Telefon</dt><dd>{{ $warranty->customer_phone_snapshot ?: '—' }}</dd><dt>Proizvod</dt><dd>{{ $warranty->product_name_snapshot }} ({{ $warranty->product_sku_snapshot ?: 'bez SKU' }})</dd><dt>Količina</dt><dd>{{ $warranty->quantity }}</dd><dt>Pravilo</dt><dd>{{ $warranty->rule?->name ?? 'Snapshot bez aktivnog pravila' }}</dd></dl></section>
@if($warranty->status!=='void')<section class="panel form-section"><h2>Serijski brojevi i rok</h2><form method="post" action="{{ route('admin.warranties.update',$warranty) }}" class="form-grid two-columns">@csrf @method('PUT')<label><span>Početak</span><input type="date" name="starts_at" value="{{ $warranty->starts_at?->format('Y-m-d') }}" required></label><label><span>Važi do</span><input type="date" name="expires_at" value="{{ $warranty->expires_at?->format('Y-m-d') }}" required></label><label class="full-width"><span>Serijski brojevi — jedan po redu</span><textarea name="serial_numbers">{{ implode("\n",$warranty->serial_numbers_json ?? []) }}</textarea></label><label class="full-width"><span>Uslovi na garantnom listu</span><textarea name="terms_snapshot">{{ $warranty->terms_snapshot }}</textarea></label><button class="button button-primary full-width" type="submit">Sačuvaj podatke</button></form></section>@endif
<section class="panel form-section"><h2>Preventivno održavanje</h2>@forelse($warranty->maintenanceRecords as $record)<article class="timeline-item"><div><strong>{{ $record->due_at?->format('d.m.Y') }} · {{ ['due'=>'Dospelo','scheduled'=>'Zakazano','completed'=>'Završeno','cancelled'=>'Otkazano'][$record->status] ?? $record->status }}</strong><p>{{ $record->result ?: $record->notes ?: 'Nema dodatne napomene.' }}</p>@if($record->service_reference)<small>Referenca: {{ $record->service_reference }}</small>@endif</div>@if(in_array($record->status,['due','scheduled'],true) && $warranty->status==='active')<div class="settings-grid"><form method="post" action="{{ route('admin.warranties.maintenance.schedule',[$warranty,$record]) }}" class="form-grid">@csrf<label><span>Termin</span><input type="datetime-local" name="scheduled_at" value="{{ $record->scheduled_at?->format('Y-m-d\TH:i') }}" required></label><input name="service_reference" placeholder="Referenca"><textarea name="notes" placeholder="Napomena"></textarea><button class="button button-ghost" type="submit">Zakaži</button></form><form method="post" action="{{ route('admin.warranties.maintenance.complete',[$warranty,$record]) }}" class="form-grid">@csrf<label><span>Završeno</span><input type="datetime-local" name="completed_at" value="{{ now()->format('Y-m-d\TH:i') }}" required></label><input name="service_reference" placeholder="Servisni nalog"><textarea name="result" required placeholder="Rezultat održavanja"></textarea><textarea name="notes" placeholder="Interna napomena"></textarea><button class="button button-primary" type="submit">Evidentiraj završetak</button></form></div>@endif</article>@empty<div class="empty-state"><p>Za ovu garanciju nije definisano preventivno održavanje.</p></div>@endforelse</section>
</div><aside class="details-side"><section class="panel form-section sticky-card"><h2>Rokovi</h2><dl class="detail-list"><dt>Početak</dt><dd>{{ $warranty->starts_at?->format('d.m.Y') }}</dd><dt>Ističe</dt><dd>{{ $warranty->expires_at?->format('d.m.Y') }}</dd><dt>Trajanje</dt><dd>{{ $warranty->duration_months ? $warranty->duration_months.' meseci' : '' }}{{ $warranty->duration_months && $warranty->duration_days ? ' + ' : '' }}{{ $warranty->duration_days ? $warranty->duration_days.' dana' : '' }}</dd><dt>Poslednje održavanje</dt><dd>{{ $warranty->last_maintenance_at?->format('d.m.Y') ?? '—' }}</dd><dt>Sledeće održavanje</dt><dd>{{ $warranty->next_maintenance_at?->format('d.m.Y') ?? '—' }}</dd></dl>@if($warranty->status==='void')<div class="alert error"><strong>Poništeno {{ $warranty->voided_at?->format('d.m.Y H:i') }}</strong><p>{{ $warranty->void_reason }}</p></div>@else<form method="post" action="{{ route('admin.warranties.void',$warranty) }}" class="form-grid" onsubmit="return confirm('Poništiti garanciju?')">@csrf<label><span>Razlog poništavanja</span><textarea name="reason" required minlength="5"></textarea></label><button class="button button-danger" type="submit">Poništi garanciju</button></form>@endif</section></aside></div>
@endsection
