@extends('layouts.app')
@section('title', 'System Health')
@section('content')
@php
    $statusLabels = ['healthy' => 'Zdravo', 'warning' => 'Upozorenje', 'critical' => 'Kritično'];
@endphp
<div class="page-heading"><div><span class="eyebrow">Produkcija i bezbednost</span><h1>System Health & Backup</h1><p>Centralni pregled baze, migracija, scheduler-a, backupa, storage-a, legacy read-only zaštite i poslednjih grešaka.</p></div><div class="header-button-row"><form method="post" action="{{ route('admin.settings.system-health.run') }}">@csrf<button class="button button-primary" type="submit">Pokreni proveru</button></form></div></div>
<div class="health-overview status-{{ $report['status'] }}"><div><small>Ukupni status</small><strong>{{ $statusLabels[$report['status']] ?? $report['status'] }}</strong><span>Provereno {{ \Carbon\Carbon::parse($report['checked_at'])->format('d.m.Y H:i:s') }}</span></div><div class="health-version"><small>Aplikacija</small><strong>v{{ $report['metrics']['app_version'] }}</strong><span>PHP {{ $report['metrics']['php_version'] }} · Laravel {{ $report['metrics']['laravel_version'] }}</span></div></div>
<div class="health-check-grid">@foreach($report['checks'] as $check)<article class="health-check status-{{ $check['status'] }}"><span class="health-dot"></span><div><strong>{{ $check['label'] }}</strong><p>{{ $check['message'] }}</p></div></article>@endforeach</div>
<div class="settings-grid health-grid">
<section class="panel form-section"><div class="card-header-row"><div><h2>Privatni backup</h2><p class="muted">MySQL dump i poslovni upload fajlovi. Lokacija mora ostati izvan public direktorijuma.</p></div></div><div class="header-button-row"><form method="post" action="{{ route('admin.settings.system-health.backup') }}">@csrf<button class="button button-primary" type="submit">Kreiraj kompletan backup</button></form><form method="post" action="{{ route('admin.settings.system-health.backup') }}">@csrf<input type="hidden" name="database_only" value="1"><button class="button button-ghost" type="submit">Samo baza</button></form><form method="post" action="{{ route('admin.settings.system-health.prune') }}">@csrf<button class="button button-ghost" type="submit">Primeni retention</button></form></div><div class="health-list">@forelse($backups as $backup)<article><div><strong>{{ $backup->backup_key }}</strong><small>{{ $backup->backup_type }} · {{ $backup->creator?->displayName() ?? 'Scheduler' }}</small></div><div><span class="status-badge status-{{ $backup->status === 'completed' ? 'active' : ($backup->status === 'failed' ? 'archived' : 'draft') }}">{{ $backup->status }}</span><small>{{ number_format(((int)$backup->size_bytes)/1048576,2,',','.') }} MB · {{ $backup->started_at?->format('d.m.Y H:i') }}</small></div></article>@empty<div class="empty-state"><p>Još nema evidentiranih backupa.</p></div>@endforelse</div></section>
<section class="panel form-section"><h2>Poslednji security događaji</h2><div class="health-list">@forelse($securityEvents as $event)<article><div><strong>{{ $event->event_type }}</strong><small>{{ $event->user?->displayName() ?? 'Gost/Sistem' }} · {{ $event->route_name ?: $event->method }}</small></div><div><span class="status-badge status-{{ $event->severity === 'critical' ? 'archived' : 'draft' }}">{{ $event->severity }}</span><small>{{ $event->created_at?->format('d.m.Y H:i:s') }}</small></div></article>@empty<div class="empty-state"><p>Nema security događaja.</p></div>@endforelse</div><a class="button button-ghost" href="{{ route('admin.audit.index',['source'=>'security']) }}">Otvori security log</a></section>
</div>
<section class="panel form-section"><h2>Istorija System Health provera</h2><div class="health-list health-snapshot-list">@forelse($snapshots as $snapshot)<article><div><strong>{{ $statusLabels[$snapshot->status] ?? $snapshot->status }}</strong><small>{{ $snapshot->checker?->displayName() ?? 'CLI/Scheduler' }}</small></div><div><span class="status-badge status-{{ $snapshot->status === 'healthy' ? 'active' : ($snapshot->status === 'critical' ? 'archived' : 'draft') }}">{{ $snapshot->status }}</span><small>{{ $snapshot->checked_at?->format('d.m.Y H:i:s') }}</small></div></article>@empty<div class="empty-state"><p>Pokreni prvu proveru da sačuvaš snapshot.</p></div>@endforelse</div></section>
@endsection
